PUT http://localhost:3001/api/courses/databaseUpdateCourse/4
Content-Type: application/json

{
    "official_course_id": "CS102",
    "course_name": "Updated from REST Computer Science",
    "kori_name": "CS102_KORI"
}
