POST http://localhost:3001/api/courses/databaseCreateCourse
Content-Type: application/json

{
    "course_code": "CS102",
    "course_name": "Advanced Computer Science",
    "course_nick_name": "Adv CS",
    "kori_name": "CS102_KORI"
}
